# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs all the lint formats"
  lane :lint do
    gradle(task: "versionCatalogFormat")
    gradle(task: "ktlintFormat")
  end

  desc "Runs all the unit tests"
  lane :unit_test do
    gradle(task: "testDebugUnitTest")
  end

end
